# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smu_sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssouser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='ssouser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='username',
        ),
        migrations.AddField(
            model_name='ssouser',
            name='nric',
            field=models.CharField(default='hello', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
