# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smu_sso', '0002_auto_20170224_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssouser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
