# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'There *is* such a thing as a free lunch'), (1, 'Stored value wallet'), (2, 'Cash on delivery')], default=0),
            preserve_default=False,
        ),
    ]
