# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.MerchantLocation'),
            preserve_default=False,
        ),
    ]
