# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'There *is* such a thing as a free lunch'), (1, 'Stored value wallet'), (2, 'Cash on delivery')], default=0),
        ),
    ]
