# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170308_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escrow_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'There *is* such a thing as a free lunch'), (1, 'Stored value wallet'), (2, 'Cash on delivery')]),
        ),
    ]
