# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170311_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='escrow_id',
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
