# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170311_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
