# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='remarks',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
