# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssouser',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='ssouser',
            name='nric',
        ),
    ]
